server:
  port: 40000


spring:
  application:
    name: game-cart

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #    sentinel:
  #      transport:
  #        #配置sentinel dashboard地址
  #        dashboard: localhost:8080

  redis:
    port: 6379
    host: 192.168.101.4
    password: 123456

  ##开启feign对sentinel的支持
  #feign:
  #  sentinel:
  #    enabled: true

  thymeleaf:
    cache: false
  session:
    store-type: redis
  servlet:
    session:
      timeout: 30m
#配置线程池
game:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#

